### PR TITLE
cleanups reported by frosted

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
libxml2 is not included in the buildout
https://github.com/plone/Products.Marshall/blob/2.0/Products/Marshall/config.py#L30

so simple xml transforms are never registered
https://github.com/plone/Products.Marshall/blob/2.0/Products/Marshall/handlers/__init__.py#L34

**Comment by jensens** [comment]
this is fine from what i can say.
test are here:
http://jenkins.plone.org/view/All/job/pull-request/150/
http://jenkins.plone.org/view/All/job/pull-request-4.3/17/

**Comment by jensens** [comment]
there seems to be a test setup problem for 4.3

**Comment by jensens** [comment]
test are here:
http://jenkins.plone.org/job/pull-request-5.0/393/
- [ ] ok
- [ ] fails

http://jenkins.plone.org/job/pull-request-4.3/105/
- [ ] ok
- [ ] fails

**Pull request merged**
